baseURL = 'https://kci.dev/'
languageCode = 'en-us'
title = 'kci-dev'
description = 'Stand alone tool for Linux Kernel developers and maintainers to interact with KernelCI'
contentDir = "docs/"

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "monokai"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      style = "monokai"

[params.ui]
sidebar_search_disable = true
navbar_logo = false
footer_about_enable = true
ul_show = 1
sidebar_menu_foldable = true
sidebar_cache_limit = 1000


[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "checkout"
    pageRef = "checkout/"
    weight = 20
  
  [[menu.main]]
    name = "config"
    pageRef = "config/"
    weight = 20
  
  [[menu.main]]
    name = "config_file"
    pageRef = "config_file/"
    weight = 20

  [[menu.main]]
    name = "testretry"
    pageRef = "testretry/"
    weight = 20

  [[menu.main]]
    name = "results"
    url = "results/"
    weight = 20
  
  [[menu.main]]
    name = "maestro-results"
    url = "maestro-results/"
    weight = 20

  [[menu.main]]
    name = "maestro-validate"
    url = "maestro-validate/"
    weight = 20

  [[menu.main]]
    name = "maestro-coverage"
    url = "maestro-coverage/"
    weight = 20
